language: python
python:
- '2.7'
install:
- pip install git+git://github.com/lojaintegrada/pyboleto
- pip install -e .
- pip install coveralls
- pip install sure
- pip install py-inspector
script:
- rm -rf .coverage
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: lojaintegrada
  password:
    secure: UMlkL/Nkw7zwB8HMx+YBcgKLgeepOIwCjAYkVGLbon2BqdBTFyaRhcHisJjhKbzGhIeMRFCy+3XEvhMJvIeUYyra+ApnbJ26AfWeTFJ5MMcQKHCBT5y1sVhyYUXJUYsPLe8GLkdZ0WyBIEKRl9/Ro6j+CGbUZkfcEe2JMHqVloQ=
  on:
    tags: true
    repo: lojaintegrada/LI-Pagador-Boleto
    all_branches: true
notifications:
  email:
    recipients:
    - contato@awsli.com.br
    - marcio.duarte@lojaintegrada.com.br
  hipchat:
    rooms:
      secure: KPqqeMN7ln+5P2SfGXo1WmJNnsKlF16NxaLvoNrlN0p4FdICpG65td4w+afh+7pvYTCC7GOu3KJ2EgZ6ZRrk+N5spQlLBjrkeOnkQDF6685ATxC8sVe9vIGxa+tUZJto4NBT6PeK2V7vCXEbRZe44CbmgH0Zljj4fnPQBLaE7Xg=
