language: python
python:
- '2.7'
install:
- pip install git+git://github.com/lojaintegrada/pyboleto
- pip install -e .
- pip install coveralls
- pip install sure
- pip install py-inspector
script:
- rm -rf .coverage
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: lojaintegrada
  password:
    secure: UMlkL/Nkw7zwB8HMx+YBcgKLgeepOIwCjAYkVGLbon2BqdBTFyaRhcHisJjhKbzGhIeMRFCy+3XEvhMJvIeUYyra+ApnbJ26AfWeTFJ5MMcQKHCBT5y1sVhyYUXJUYsPLe8GLkdZ0WyBIEKRl9/Ro6j+CGbUZkfcEe2JMHqVloQ=
  on:
    tags: true
    repo: lojaintegrada/LI-Pagador-Boleto
    all_branches: true
notifications:
  email:
    recipients:
    - contato@awsli.com.br
    - marcio.duarte@lojaintegrada.com.br
